var files_dup =
[
    [ "absolute_error.h", "absolute__error_8h.html", "absolute__error_8h" ],
    [ "advection.h", "advection_8h.html", "advection_8h" ],
    [ "epsilon.h", "epsilon_8h.html", "epsilon_8h" ],
    [ "euler.h", "euler_8h.html", "euler_8h" ],
    [ "advection/CMakeFiles/feature_tests.cxx", "advection_2CMakeFiles_2feature__tests_8cxx.html", "advection_2CMakeFiles_2feature__tests_8cxx" ],
    [ "cgPoisson/CMakeFiles/feature_tests.cxx", "cgPoisson_2CMakeFiles_2feature__tests_8cxx.html", "cgPoisson_2CMakeFiles_2feature__tests_8cxx" ],
    [ "diffCoeff/CMakeFiles/feature_tests.cxx", "diffCoeff_2CMakeFiles_2feature__tests_8cxx.html", "diffCoeff_2CMakeFiles_2feature__tests_8cxx" ],
    [ "epsilon/CMakeFiles/feature_tests.cxx", "epsilon_2CMakeFiles_2feature__tests_8cxx.html", "epsilon_2CMakeFiles_2feature__tests_8cxx" ],
    [ "error/CMakeFiles/feature_tests.cxx", "error_2CMakeFiles_2feature__tests_8cxx.html", "error_2CMakeFiles_2feature__tests_8cxx" ],
    [ "explicitEulerDeux/CMakeFiles/feature_tests.cxx", "explicitEulerDeux_2CMakeFiles_2feature__tests_8cxx.html", "explicitEulerDeux_2CMakeFiles_2feature__tests_8cxx" ],
    [ "FDMMatrix/CMakeFiles/feature_tests.cxx", "FDMMatrix_2CMakeFiles_2feature__tests_8cxx.html", "FDMMatrix_2CMakeFiles_2feature__tests_8cxx" ],
    [ "heatEquation/CMakeFiles/feature_tests.cxx", "heatEquation_2CMakeFiles_2feature__tests_8cxx.html", "heatEquation_2CMakeFiles_2feature__tests_8cxx" ],
    [ "implicitExperiment/CMakeFiles/feature_tests.cxx", "implicitExperiment_2CMakeFiles_2feature__tests_8cxx.html", "implicitExperiment_2CMakeFiles_2feature__tests_8cxx" ],
    [ "logistic/CMakeFiles/feature_tests.cxx", "logistic_2CMakeFiles_2feature__tests_8cxx.html", "logistic_2CMakeFiles_2feature__tests_8cxx" ],
    [ "numericalExperiments/CMakeFiles/feature_tests.cxx", "numericalExperiments_2CMakeFiles_2feature__tests_8cxx.html", "numericalExperiments_2CMakeFiles_2feature__tests_8cxx" ],
    [ "predictorCorrector/CMakeFiles/feature_tests.cxx", "predictorCorrector_2CMakeFiles_2feature__tests_8cxx.html", "predictorCorrector_2CMakeFiles_2feature__tests_8cxx" ],
    [ "predictorExperiment/CMakeFiles/feature_tests.cxx", "predictorExperiment_2CMakeFiles_2feature__tests_8cxx.html", "predictorExperiment_2CMakeFiles_2feature__tests_8cxx" ],
    [ "rungeExperiment/CMakeFiles/feature_tests.cxx", "rungeExperiment_2CMakeFiles_2feature__tests_8cxx.html", "rungeExperiment_2CMakeFiles_2feature__tests_8cxx" ],
    [ "rungeKutta/CMakeFiles/feature_tests.cxx", "rungeKutta_2CMakeFiles_2feature__tests_8cxx.html", "rungeKutta_2CMakeFiles_2feature__tests_8cxx" ],
    [ "springMass/CMakeFiles/feature_tests.cxx", "springMass_2CMakeFiles_2feature__tests_8cxx.html", "springMass_2CMakeFiles_2feature__tests_8cxx" ],
    [ "testCases/CMakeFiles/feature_tests.cxx", "testCases_2CMakeFiles_2feature__tests_8cxx.html", "testCases_2CMakeFiles_2feature__tests_8cxx" ],
    [ "image.h", "image_8h.html", "image_8h" ],
    [ "logistic.h", "logistic_8h.html", "logistic_8h" ],
    [ "matrix.h", "matrix_8h.html", "matrix_8h" ],
    [ "predictorCorrector.h", "predictorCorrector_8h.html", "predictorCorrector_8h" ],
    [ "relative_error.h", "relative__error_8h.html", "relative__error_8h" ],
    [ "rungeKutta.h", "rungeKutta_8h.html", "rungeKutta_8h" ],
    [ "springMass.h", "springMass_8h.html", "springMass_8h" ],
    [ "testCases.h", "testCases_8h.html", "testCases_8h" ]
];